config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/profile'

  get '/auth/:provider/callback' , to: "sessions#create"

  delete 'sign_out' , to: "sessions#destroy" , as: "sign_out"

end

app/models/user.rb
class User < ActiveRecord::Base

	def self.sign_in_from_omniauth(auth)
		find_by(provider: auth['provider'],uid: auth['uid']) || create_user_from_omniauth(auth)
	end

	def self.create_user_from_omniauth(auth)
		create(
			provider: auth['provider'],
			uid: 	  auth['uid'],
			name:     auth['info']['name']
		)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
    # puts 'moh' ******* can't print out , if u print out current_user record will alwyas be nil
    rescue ActiveRecord::RecordNotFound
  end


  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :set_auth 
before_action :require_login , only: [:profile]
# make sure it is only authenticate profile page and not index page
#  if u authenticate all pages, it will cause loop hole error

  def index
  	if current_user
		redirect_to home_profile_path
	end
  end

  def profile
  end

  private
  def set_auth
  	@auth = session[:omniauth] if session[:omniauth]
  end


  # Returns true if the user is logged in, false otherwise.
  def authenticate_user?
     !current_user.nil?
  end

  def require_login
    unless authenticate_user?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path # halts request cycle
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		auth = request.env['omniauth.auth']
		session[:omniauth] = auth.except('extra')
		
		user = User.sign_in_from_omniauth(auth)

		
		session[:user_id]  = user.id

		redirect_to root_url, notice: "Signed in successfully"
	end

	def destroy
		session[:omniauth] = nil
		session[:user_id] = nil

		redirect_to root_url, notice: "Signed out successfully"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/profile.html.erb
<h2>Profile Page</h2>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Omni" , root_path , class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
   
        <% if current_user %>
          <li>Sign in as :<%= current_user.name %> - <%= image_tag(@auth['info']['image'], width: '50', class: 'img-circle') %></li>
          <li><%= link_to "Sign Out" ,  sign_out_path , method: :delete %></li>
        <% else %>
          <li><%= link_to "auth/facebook" do %><%= image_tag('facebook.png', width: '40' ,class: 'img-circle')  %> <% end %></li>
          <li><%= link_to "auth/github" do  %><%= image_tag('github.png', width: '40' , class: 'img-circle' ) %>
            <% end %></li>
          <li><%= link_to "auth/twitter" do  %><%= image_tag('twitter.png', width: '40' , class: 'img-circle' ) %>
            <% end %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmniAuthFromStuk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |key,value| %>
	<div class="alert alert-info">
		<%= value %>
	</div>
<% end %>

<% if current_user %>
	<div class="text-center">
		<h1>Welcome, <%= current_user.name %></h1>
	
	</div>
<% end %>
<%= yield %>

</body>
</html>